### ISSUE TITLE
Connect Petitions to Database

### ISSUE THREAD

**Issue by bristola** [GatorEducator/petition-pronto#12]
We need two functions in the *database_handler.py* file:

1. *get_petitions(email)*: This function will connect to the database and get a list of all petitions associated with the department of the input email. The output of this function should be a Python list of dictionaries. An example output should look like the following:

```
[{'id':1,'name':"Austin Bristol",'email':"bristola@allegheny.edu",'department':'Computer Science'},{'id':2,'name':'Bob','email':'bob@allegheny.edu','department':'Computer Science'}]
```

1. *get_petition_info(id)*: This function will connect to the database and get information about a specific petition; the one associated with the input ID. The output should be a Python dictionary in the following format:

```
{'id':id,'name':"Austin Bristol",'email':"bristola@allegheny.edu",'department':'Computer Science','content':'This is some petition for something.'}
```

**Comment by lussierc** [comment]
I have begun work on this issue in [this branch](https://github.com/GatorEducator/petition-pronto/tree/connect-petitions-to-database).

**Comment by lussierc** [comment]
Pull Request #14 closes this issue.
