### ISSUE TITLE
Need a function to submit professor approvals

### ISSUE THREAD

**Issue by bristola** [GatorEducator/petition-pronto#21]
We need a new table in the database to hold all the professor responses to the petitions. Also, we need a function in the *database_updater.py* that adds new responses to that table.

**Comment by lussierc** [comment]
I will work on this. I think this is somewhat similar to Issue #7.

**Comment by lussierc** [comment]
Work has begun on this idea in [this branch](https://github.com/GatorEducator/petition-pronto/tree/approval-functionality).

**Comment by lussierc** [comment]
The branch mentioned above was merged into master.
